# 向量和矩阵乘法

In [1]:
import torch
import numpy as np

## 向量乘法

![](https://bj.bcebos.com/ipic/dot-product_and_cross-product.png)

In [2]:
a = torch.arange(1, 4)
b = torch.arange(4, 7)

In [3]:
a, b

(tensor([1, 2, 3]), tensor([4, 5, 6]))

### 内积（dot product）

In [4]:
torch.dot(a, b)

tensor(32)

### 外积（cross product）

In [5]:
torch.cross(a, b)

tensor([-3,  6, -3])

## 矩阵乘法

In [6]:
x = torch.arange(1, 7).reshape((2, 3))
y = torch.arange(1, 7).reshape((3, 2))

In [7]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
y

tensor([[1, 2],
        [3, 4],
        [5, 6]])

### 矩阵乘法

`torch.mm`、`torch.matmul`和`@`等价

In [9]:
torch.mm(x, y)

tensor([[22, 28],
        [49, 64]])

In [10]:
torch.matmul(x, y)

tensor([[22, 28],
        [49, 64]])

In [11]:
x @ y

tensor([[22, 28],
        [49, 64]])

### batch矩阵乘法

In [12]:
bx = torch.arange(1, 13).reshape(2, 2, 3)
by = torch.arange(1, 13).reshape(2, 3, 2)

In [13]:
bx

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [14]:
by

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [15]:
torch.bmm(bx, by)

tensor([[[ 22,  28],
         [ 49,  64]],

        [[220, 244],
         [301, 334]]])

### 矩阵点乘

`torch.mul`和`*`等价

In [16]:
torch.mul(x.reshape((2, 3)), y.reshape((2, 3)))

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [17]:
x.reshape((2, 3)) * y.reshape((2, 3))

tensor([[ 1,  4,  9],
        [16, 25, 36]])

## 参考文献

* https://www.whcsrl.com/blog/1296
* https://www.cnblogs.com/long5683/p/11217466.html